Catch and log failing to bind and connect to the unix domain socket
fixes a panic that breaks request processing in rails if the bind
failed:

thread '<unnamed>' panicked at pyroscope_ffi/ruby/ext/rbspy/src/lib.rs:291:64:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: add_thread_tag
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: rbffi_CallFunction
   8: <unknown>
   9: vm_call_cfunc_with_frame_
             at /usr/src/ruby/vm_insnhelper.c:3801:12